server:
  port: 8080

app:
  aggregation:
    interval-ms: 10000
    symbols: [ BTCUSDT, ETHUSDT ]
    binance-url: https://api.binance.com/api/v3/ticker/bookTicker
    huobi-url: https://api.huobi.pro/market/tickers

spring:
  flyway:
    enabled: true

  datasource:
    url: jdbc:h2:mem:cryptodb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console # url: http://localhost:8080/h2-console/

logging:
  level:
    org.hibernate.SQL: error